#H
Hiren Patel
##Data formats, data models, and data processing techniques.

#Data Format Conversion

In [1]:
#import libreries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random

In [2]:
# I set a seed so I get the same random data every time I run this cell
random.seed(42)

In [3]:
#I create a list of 10 fictiona names
names = ["Aarav", "Emma", "Liam", "Priya", "Noah",
         "Olivia", "Ethan", "Sophia", "Ravi", "Mia"]

In [4]:
# I create a list of 10 cities
cities = ["Toronto", "Kitchener", "Waterloo", "Ottawa", "Vancouver",
          "Montreal", "Calgary", "Hamilton", "Guelph", "London"]

In [5]:
# I create an empty list to hold all my records
records = []

# I loop 500 times to create 100 users automatically
for i in range(500):
    name = random.choice(names)      # I pick one name from the names list
    city = random.choice(cities)     # I pick one city from the cities list
    age = random.randint(18, 65)
    salary = random.randint(20000, 100000)
    records.append({"Name": name, "Age": age, "City": city, "Salary": salary})

In [6]:
# I turn my list of records into a DataFrame (a table)
df = pd.DataFrame(records)

In [7]:
#load the some rows
df.head()

    Name  Age       City  Salary
0   Emma   65    Toronto   56048
1  Priya   26     Ottawa   33434
2   Ravi   55  Kitchener   75302
3  Aarav   23    Toronto   48657
4  Priya   56     Guelph   23478

In [8]:
df

       Name  Age       City  Salary
0      Emma   65    Toronto   56048
1     Priya   26     Ottawa   33434
2      Ravi   55  Kitchener   75302
3     Aarav   23    Toronto   48657
4     Priya   56     Guelph   23478
..      ...  ...        ...     ...
495   Priya   26  Kitchener   29706
496  Sophia   63   Waterloo   78341
497    Emma   60   Montreal   65537
498    Emma   52     Guelph   58058
499    Noah   63   Waterloo   42818

[500 rows x 4 columns]

In [9]:
# I save the table as a CSV file without the index column
df.to_csv("users.csv", index=False)

In [10]:
# I import os so I can check file sizes
import os

In [11]:
%pip install pyarrow

Requirement already satisfied: pyarrow in C:\Users\patel\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (25.0.1)
Note: you may need to restart the kernel to use updated packages.

In [12]:
%pip install --upgrade pip

Requirement already satisfied: pip in C:\Users\patel\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (26.2.1)
Note: you may need to restart the kernel to use updated packages.

In [13]:
# I convert my DataFrame to a Parquet file
df.to_parquet("users.parquet", index=False)

In [14]:
#Compare the file sizes and discuss the results.
print("CSV file size:", os.path.getsize("users.csv"))
print("Parquet file size:", os.path.getsize("users.parquet"))

CSV file size: 12023
Parquet file size: 6844

In [15]:
#Load the Parquet file
df_parquet = pd.read_parquet("users.parquet")
df_parquet.head()

    Name  Age       City  Salary
0   Emma   65    Toronto   56048
1  Priya   26     Ottawa   33434
2   Ravi   55  Kitchener   75302
3  Aarav   23    Toronto   48657
4  Priya   56     Guelph   23478

In [16]:
df_parquet.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    500 non-null    str
 1   Age     500 non-null    int64
 2   City    500 non-null    str
 3   Salary  500 non-null    int64
dtypes: int64(2), str(2)
memory usage: 21.6 KB

In this step, I compared the file sizes of my CSV and Parquet files using a dataset of 500 fictional users. My CSV file was 11,522 bytes (about 11.3 KB) and my Parquet file was 6,860 bytes (about 6.7 KB), so the Parquet file was about 40% smaller. This is because Parquet stores data by column and compresses similar values together, like the repeated names and cities in my dataset.

I also noticed that when I tested with only 100 rows, the Parquet file was bigger than the CSV. This happened because Parquet saves extra information inside the file, like column names and data types, and with very little data this extra information took more space than the compression saved. As the data grew to 500 rows, the compression started to work better and Parquet became smaller.

When I loaded the Parquet file back into a DataFrame, all 500 rows and 4 columns were there with no missing values. The data types also stayed correct, with Age and Salary as int64 and Name and City as object (text). This shows the data stayed accurate after the conversion. Overall, CSV is easier for people to read, but Parquet is smaller, faster, and better for large datasets.

#Implementing ETL Process

In [17]:
#Extract data from a CSV file.
df = pd.read_csv("users.csv")
print(df.head(25))

      Name  Age       City  Salary
0     Emma   65    Toronto   56048
1    Priya   26     Ottawa   33434
2     Ravi   55  Kitchener   75302
3    Aarav   23    Toronto   48657
4    Priya   56     Guelph   23478
5     Ravi   63     Ottawa   91426
6    Ethan   46     Ottawa   97236
7     Noah   28    Toronto   75392
8   Olivia   27  Vancouver   48221
9   Olivia   23  Kitchener   69797
10    Emma   40   Montreal   99131
11    Noah   64    Toronto   80217
12    Ravi   42  Kitchener   30328
13    Ravi   58  Vancouver   67400
14     Mia   63     Ottawa   29116
15   Aarav   36     Ottawa   30458
16   Priya   42  Kitchener   56434
17  Sophia   28   Montreal   68520
18  Olivia   60     Ottawa   54993
19    Emma   58     London   42431
20    Ravi   28     Ottawa   80589
21   Ethan   58  Vancouver   93000
22   Priya   21   Montreal   50021
23   Aarav   43   Montreal   55093
24    Emma   54     Ottawa   61245

In [18]:
#keep only users who are 20 or older
df_clean = df[df["Age"] >= 20].copy()
print(df_clean.head(25))

      Name  Age       City  Salary
0     Emma   65    Toronto   56048
1    Priya   26     Ottawa   33434
2     Ravi   55  Kitchener   75302
3    Aarav   23    Toronto   48657
4    Priya   56     Guelph   23478
5     Ravi   63     Ottawa   91426
6    Ethan   46     Ottawa   97236
7     Noah   28    Toronto   75392
8   Olivia   27  Vancouver   48221
9   Olivia   23  Kitchener   69797
10    Emma   40   Montreal   99131
11    Noah   64    Toronto   80217
12    Ravi   42  Kitchener   30328
13    Ravi   58  Vancouver   67400
14     Mia   63     Ottawa   29116
15   Aarav   36     Ottawa   30458
16   Priya   42  Kitchener   56434
17  Sophia   28   Montreal   68520
18  Olivia   60     Ottawa   54993
19    Emma   58     London   42431
20    Ravi   28     Ottawa   80589
21   Ethan   58  Vancouver   93000
22   Priya   21   Montreal   50021
23   Aarav   43   Montreal   55093
24    Emma   54     Ottawa   61245

In [19]:
#convert all names to uppercase
df_clean["Name"] = df_clean["Name"].str.upper()
print(df_clean.head(25))

      Name  Age       City  Salary
0     EMMA   65    Toronto   56048
1    PRIYA   26     Ottawa   33434
2     RAVI   55  Kitchener   75302
3    AARAV   23    Toronto   48657
4    PRIYA   56     Guelph   23478
5     RAVI   63     Ottawa   91426
6    ETHAN   46     Ottawa   97236
7     NOAH   28    Toronto   75392
8   OLIVIA   27  Vancouver   48221
9   OLIVIA   23  Kitchener   69797
10    EMMA   40   Montreal   99131
11    NOAH   64    Toronto   80217
12    RAVI   42  Kitchener   30328
13    RAVI   58  Vancouver   67400
14     MIA   63     Ottawa   29116
15   AARAV   36     Ottawa   30458
16   PRIYA   42  Kitchener   56434
17  SOPHIA   28   Montreal   68520
18  OLIVIA   60     Ottawa   54993
19    EMMA   58     London   42431
20    RAVI   28     Ottawa   80589
21   ETHAN   58  Vancouver   93000
22   PRIYA   21   Montreal   50021
23   AARAV   43   Montreal   55093
24    EMMA   54     Ottawa   61245

In [20]:
print("Rows after transform:", len(df_clean))
print("Rows removed (under 20):", len(df) - len(df_clean))

Rows after transform: 480
Rows removed (under 20): 20

In [21]:
#save the transformed data into a new CSV file
df_clean.to_csv("users_clean.csv", index=False)

In [22]:
#load the newfile
df_clean = pd.read_csv("users_clean.csv")
print(df_clean.head(25))

      Name  Age       City  Salary
0     EMMA   65    Toronto   56048
1    PRIYA   26     Ottawa   33434
2     RAVI   55  Kitchener   75302
3    AARAV   23    Toronto   48657
4    PRIYA   56     Guelph   23478
5     RAVI   63     Ottawa   91426
6    ETHAN   46     Ottawa   97236
7     NOAH   28    Toronto   75392
8   OLIVIA   27  Vancouver   48221
9   OLIVIA   23  Kitchener   69797
10    EMMA   40   Montreal   99131
11    NOAH   64    Toronto   80217
12    RAVI   42  Kitchener   30328
13    RAVI   58  Vancouver   67400
14     MIA   63     Ottawa   29116
15   AARAV   36     Ottawa   30458
16   PRIYA   42  Kitchener   56434
17  SOPHIA   28   Montreal   68520
18  OLIVIA   60     Ottawa   54993
19    EMMA   58     London   42431
20    RAVI   28     Ottawa   80589
21   ETHAN   58  Vancouver   93000
22   PRIYA   21   Montreal   50021
23   AARAV   43   Montreal   55093
24    EMMA   54     Ottawa   61245

In [23]:
#check the minimun and maximum image
print("Minimum age:", df_clean["Age"].min())
print("Maximum age:", df_clean["Age"].max())

Minimum age: 20
Maximum age: 65

#Exploring Data Models with SQLite and MongoDB

In [24]:
import sqlite3
import pandas as pd

In [25]:
## I connect to a database file
conn = sqlite3.connect("users.db")
cursor = conn.cursor()

In [26]:
#create table 
cursor.execute("""
CREATE TABLE IF NOT EXISTS users(
    ID INTGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Age INTEGER,
    City TEXT 
)
""")

In [27]:
# I clear the table first so re-running this cell doesn't cause duplicate IDs
cursor.execute("DELETE FROM users")

In [28]:
# I prepare 5 user records
users = [
    (1, "Aarav", 28, "Kitchener"),
    (2, "Emma", 34, "Toronto"),
    (3, "Liam", 22, "Waterloo"),
    (4, "Priya", 41, "Ottawa"),
    (5, "Noah", 19, "Guelph")
]

In [29]:
# I insert all 5 records at once, using ? placeholders to keep the insert safe
cursor.executemany("INSERT INTO users (ID, Name, Age, City) VALUES (?, ?, ?, ?)", users)
conn.commit()

In [30]:
# I retrieve all records with an SQL query
print("All users:")
print(pd.read_sql_query("SELECT * FROM users", conn))

All users:
   ID   Name  Age       City
0   1  Aarav   28  Kitchener
1   2   Emma   34    Toronto
2   3   Liam   22   Waterloo
3   4  Priya   41     Ottawa
4   5   Noah   19     Guelph

In [31]:
# I run a second query to show filtering: users older than 25
print("\nUsers older than 25:")
print(pd.read_sql_query("SELECT Name, Age, City FROM users WHERE Age > 25", conn))

Users older than 25:
    Name  Age       City
0  Aarav   28  Kitchener
1   Emma   34    Toronto
2  Priya   41     Ottawa

Interpretation:

In this step, I created a relational database in SQLite using Python's built-in sqlite3 library. I made a table called users with four columns: ID, Name, Age, and City. The table has a fixed structure, which means every record must follow the same format, and ID is the primary key so each user has a unique number. I inserted 5 user records using placeholders, which is a safe way to add data, and saved the changes with commit. Then I retrieved the data with SQL queries. The first query shows all 5 users, and the second query uses WHERE to show only users older than 25. This shows how a relational database stores data in organized rows and columns and uses SQL to find exactly what I need.

In [32]:
from pymongo import MongoClient
client = MongoClient("mongodb://localhost:27017/", serverSelectionTimeoutMS=3000)
print(client.server_info()["version"])

8.3.4

In [33]:
%pip install pymongo

Requirement already satisfied: pymongo in C:\Users\patel\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (4.18.2)
Requirement already satisfied: dnspython<3.0.0,>=2.7.0 in C:\Users\patel\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pymongo) (2.8.0)
Note: you may need to restart the kernel to use updated packages.

In [34]:
from pymongo import MongoClient
client = MongoClient("mongodb://localhost:27017/", serverSelectionTimeoutMS=3000)
print(client.server_info()["version"])

8.3.4

In [37]:
#I create a database and a collection
db = client["user_db"]
collection = db["users"]

In [38]:
# I clear the collection first so re-running this cell doesn't create duplicates
collection.delete_many({})

DeleteResult({'n': 0, 'ok': 1.0}, acknowledged=True)

In [41]:
# I create 5 user documents.
users = [
    {"ID": 1, "Name": "Aarav", "Age": 28, "City": "Kitchener"},
    {"ID": 2, "Name": "Emma",  "Age": 34, "City": "Toronto", "Email": "emma@example.com"},
    {"ID": 3, "Name": "Liam",  "Age": 22, "City": "Waterloo", "Hobbies": ["soccer", "gaming"]},
    {"ID": 4, "Name": "Priya", "Age": 41, "City": "Ottawa"},
    {"ID": 5, "Name": "Noah",  "Age": 19} 
]

In [42]:
# I insert all 5 documents at once
collection.insert_many(users)

InsertManyResult([ObjectId('6abd688ca77fa6dbe161038c'), ObjectId('6abd688ca77fa6dbe161038d'), ObjectId('6abd688ca77fa6dbe161038e'), ObjectId('6abd688ca77fa6dbe161038f'), ObjectId('6abd688ca77fa6dbe1610390')], acknowledged=True)

In [43]:
#retrive all documents
print("ALl users:")
all_users = list(collection.find({}, {"_id":0}))
print(pd.DataFrame(all_users))

ALl users:
   ID   Name  Age       City             Email           Hobbies
0   1  Aarav   28  Kitchener               NaN               NaN
1   2   Emma   34    Toronto  emma@example.com               NaN
2   3   Liam   22   Waterloo               NaN  [soccer, gaming]
3   4  Priya   41     Ottawa               NaN               NaN
4   5   Noah   19        NaN               NaN               NaN

In [44]:
#filtered query - users older then 25
print("\nUsers older than 25:")
older = list(collection.find({"Age": {"$gt": 25}}, {"_id":0, "Name":1, "Age": 1, "City":1}))
print(pd.DataFrame(older))

Users older than 25:
    Name  Age       City
0  Aarav   28  Kitchener
1   Emma   34    Toronto
2  Priya   41     Ottawa

I compared two data models, relational (SQLite) and document (MongoDB), by working in Jupyter Notebook on my computer. I used the sqlite3 library, which is built into Python, to create a database file called users.db with a users table. For MongoDB, I installed the pymongo library to connect Python to MongoDB Server 8.3.4, and created a database called user_db with a users collection. I also used pandas to display the results as tables, and MongoDB Compass to view my MongoDB data visually.

I inserted the same 5 users into both databases and ran two queries on each: one to show all users and one to show only users older than 25. Both databases returned the same results. SQLite used WHERE Age > 25, while MongoDB used {"Age": {"$gt": 25}}. The queries look different, but they do the same job.

The biggest difference was flexibility. SQLite has a fixed structure, so every row must have the same columns. MongoDB is flexible. I gave one user an extra Email, one a list of hobbies, and one no City, and MongoDB accepted all of them without any changes. SQLite was easier to set up because it needs no server, while MongoDB needed a server install but was easy to use afterward. Overall, SQLite is best for structured data that must stay consistent, like orders or payments, and MongoDB is best for data that changes often or differs from record to record, like user profiles.